"""Add agreements

Revision ID: 29341199f21b
Revises: 9fd424923f1d
Create Date: 2026-02-25 17:50:31.038198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29341199f21b'
down_revision = '9fd424923f1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exhibitor_access_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exhibitor_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exhibitor_id'], ['exhibitor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('exhibitor_agreement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exhibitor_id', sa.Integer(), nullable=False),
    sa.Column('accepted_reglamento', sa.Boolean(), nullable=True),
    sa.Column('accepted_carta_responsiva', sa.Boolean(), nullable=True),
    sa.Column('signer_name', sa.String(length=120), nullable=False),
    sa.Column('signature_image_path', sa.String(length=300), nullable=True),
    sa.Column('pdf_path', sa.String(length=300), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=60), nullable=True),
    sa.Column('user_agent', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exhibitor_id'], ['exhibitor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exhibitor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exhibitor_agreement')
    op.drop_table('exhibitor_access_token')
    # ### end Alembic commands ###
