"""add paid column to competition_participant

Revision ID: 8404c4711de9
Revises: 
Create Date: 2026-03-08 23:35:24.734836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8404c4711de9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competition_participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competition_participant', schema=None) as batch_op:
        batch_op.drop_column('paid')

    # ### end Alembic commands ###
