"""add organization model

Revision ID: 8aa48bf6473a
Revises: ce39bd776d5f
Create Date: 2026-02-26 18:54:18.930747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aa48bf6473a'
down_revision = 'ce39bd776d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('festival', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('festival_owner_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'organization', ['organization_id'], ['id'])
        batch_op.drop_column('owner_user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'organization', ['organization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('festival', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('festival_owner_user_id_fkey'), 'user', ['owner_user_id'], ['id'])
        batch_op.drop_column('organization_id')

    op.drop_table('organization')
    # ### end Alembic commands ###
