"""Add exhibitor documents

Revision ID: 924eea26a451
Revises: 29341199f21b
Create Date: 2026-02-25 23:51:45.095837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924eea26a451'
down_revision = '29341199f21b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exhibitor_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exhibitor_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exhibitor_id'], ['exhibitor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exhibitor_document')
    # ### end Alembic commands ###
