"""Add electrical requirements and equipment items

Revision ID: 9fd424923f1d
Revises: 9120ef187083
Create Date: 2026-02-25 17:07:33.986999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd424923f1d'
down_revision = '9120ef187083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('electrical_requirement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exhibitor_id', sa.Integer(), nullable=False),
    sa.Column('total_amperage', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('voltage', sa.String(length=10), nullable=True),
    sa.Column('needs_220', sa.Boolean(), nullable=True),
    sa.Column('own_generator', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exhibitor_id'], ['exhibitor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exhibitor_id')
    )
    op.create_table('equipment_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exhibitor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('watts', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exhibitor_id'], ['exhibitor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment_item')
    op.drop_table('electrical_requirement')
    # ### end Alembic commands ###
